name: SecurePay
options:
  bundleIdPrefix: com.hackHers
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  SecurePay:
    type: application
    platform: iOS
    sources:
      - SecurePay
    info:
      path: SecurePay/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hackHers.securepay
        INFOPLIST_FILE: SecurePay/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: NO
    scheme:
      testTargets: []
      gatherCoverageData: false
